lappend VEWarning0 {source "/home/vgr16/nfshome/face_with_corner/src/cv/my_ocv_sw.cpp" severity 3 Warning "Unsupported virtual function 'operator ()' with class 'BackgroundSubtractor' in file '/home/vgr16/homedir/ZYBO_SDSoC_platforms-master/2015.4/zybo_hdmi_in/arm-xilinx-linux-gnueabi/include/opencv2/video/background_segm.hpp' on line '63': Virtual operator override function."}
lappend VEWarning1 {source "/home/vgr16/nfshome/face_with_corner/src/cv/my_ocv_sw.cpp" severity 3 Warning "Unsupported virtual function 'operator ()' with class 'BackgroundSubtractorMOG' in file '/home/vgr16/homedir/ZYBO_SDSoC_platforms-master/2015.4/zybo_hdmi_in/arm-xilinx-linux-gnueabi/include/opencv2/video/background_segm.hpp' on line '91': Virtual operator override function."}
lappend VEWarning2 {source "/home/vgr16/nfshome/face_with_corner/src/cv/my_ocv_sw.cpp" severity 3 Warning "Unsupported virtual function 'operator ()' with class 'BackgroundSubtractorMOG2' in file '/home/vgr16/homedir/ZYBO_SDSoC_platforms-master/2015.4/zybo_hdmi_in/arm-xilinx-linux-gnueabi/include/opencv2/video/background_segm.hpp' on line '128': Virtual operator override function."}
lappend VEWarning3 {source "/home/vgr16/nfshome/face_with_corner/src/cv/my_ocv_sw.cpp" severity 3 Warning "Unsupported virtual function 'operator ()' with class 'BackgroundSubtractorGMG' in file '/home/vgr16/homedir/ZYBO_SDSoC_platforms-master/2015.4/zybo_hdmi_in/arm-xilinx-linux-gnueabi/include/opencv2/video/background_segm.hpp' on line '222': Virtual operator override function."}
lappend VEWarning4 {source "/home/vgr16/nfshome/face_with_corner/src/cv/my_ocv_sw.cpp" severity 3 Warning "Unsupported virtual function 'operator ()' with class 'Feature2D' in file '/home/vgr16/homedir/ZYBO_SDSoC_platforms-master/2015.4/zybo_hdmi_in/arm-xilinx-linux-gnueabi/include/opencv2/features2d/features2d.hpp' on line '261': Virtual operator override function."}
lappend VEWarning5 {source "/home/vgr16/nfshome/face_with_corner/src/cv/my_ocv_sw.cpp" severity 3 Warning "Unsupported virtual function 'operator ()' with class 'Feature2D' in file '/home/vgr16/homedir/ZYBO_SDSoC_platforms-master/2015.4/zybo_hdmi_in/arm-xilinx-linux-gnueabi/include/opencv2/features2d/features2d.hpp' on line '261': Virtual operator override function."}
lappend VEWarning6 {source "/home/vgr16/nfshome/face_with_corner/src/cv/my_ocv_sw.cpp" severity 3 Warning "Unsupported dynamic polymorphism CPP method 'FREAK' with class 'FREAK' in file '/home/vgr16/homedir/ZYBO_SDSoC_platforms-master/2015.4/zybo_hdmi_in/arm-xilinx-linux-gnueabi/include/opencv2/features2d/features2d.hpp' on line '424': Class CTOR is dynamic poly function."}
lappend VEWarning7 {source "/home/vgr16/nfshome/face_with_corner/src/cv/my_ocv_sw.cpp" severity 3 Warning "Unsupported dynamic polymorphism CPP method 'DynamicAdaptedFeatureDetector' with class 'DynamicAdaptedFeatureDetector' in file '/home/vgr16/homedir/ZYBO_SDSoC_platforms-master/2015.4/zybo_hdmi_in/arm-xilinx-linux-gnueabi/include/opencv2/features2d/features2d.hpp' on line '800': Class CTOR is dynamic poly function."}
lappend VEWarning8 {source "/home/vgr16/nfshome/face_with_corner/src/cv/my_ocv_sw.cpp" severity 3 Warning "Unsupported virtual function 'getMat' with class '_InputArray' in file '/home/vgr16/homedir/ZYBO_SDSoC_platforms-master/2015.4/zybo_hdmi_in/arm-xilinx-linux-gnueabi/include/opencv2/core/mat.hpp' on line '762': Unrecognized the Caller expression."}
lappend VEWarning9 {source "/home/vgr16/nfshome/face_with_corner/src/cv/my_ocv_sw.cpp" severity 3 Warning "Unsupported virtual function 'getMat' with class '_InputArray' in file '/home/vgr16/homedir/ZYBO_SDSoC_platforms-master/2015.4/zybo_hdmi_in/arm-xilinx-linux-gnueabi/include/opencv2/core/mat.hpp' on line '765': Unrecognized the Caller expression."}
lappend VEWarning10 {source "/home/vgr16/nfshome/face_with_corner/src/cv/my_ocv_sw.cpp" severity 3 Warning "Unsupported virtual function 'create' with class '_OutputArray' in file '/home/vgr16/homedir/ZYBO_SDSoC_platforms-master/2015.4/zybo_hdmi_in/arm-xilinx-linux-gnueabi/include/opencv2/core/mat.hpp' on line '764': Unrecognized the Caller expression."}
